---

- name: Create temporary directory
  ansible.builtin.tempfile:
    state: directory
  register: aws_cli_temp

- name: Extract AWS CLI installer to temporary directory
  ansible.builtin.unarchive:
    remote_src: yes
    src: "{{ aws_cli_url }}"
    dest: "{{ aws_cli_temp.path }}"

- name: Install AWS CLI
  ansible.builtin.command:
    cmd: "sh {{ aws_cli_temp }}/aws/install"

- name: Remove temporary directory
  ansible.builtin.file:
    path: "{{ aws_cli_temp.path }}"
    state: absent
